Saving last configuration file to .certora_internal/23_11_19_00_21_08_568/run.conf
Default package file package.json not found, external contract dependencies could be unresolved. Ignore if solc invocation was successful
There is no TAC file. Going to script EVMVerifier/certoraBuild.py to main_with_args()
Creating dir /Users/nileshgupta/Desktop/Algorand/gearbot/contracts/.certora_internal/23_11_19_00_21_08_568/.certora_config
In /Users/nileshgupta/Desktop/Algorand/gearbot/contracts/certora/spec/GearSparkbot.spec, found the imports: []
copying spec file /Users/nileshgupta/Desktop/Algorand/gearbot/contracts/certora/spec/GearSparkbot.spec to /Users/nileshgupta/Desktop/Algorand/gearbot/contracts/.certora_internal/23_11_19_00_21_08_568/.certora_sources/.0_GearSparkbot.spec.spec
writing /Users/nileshgupta/Desktop/Algorand/gearbot/contracts/.certora_internal/23_11_19_00_21_08_568/.certora_verify.json

building file src/GearSparkbot.sol
Running cmd /Users/nileshgupta/.nvm/versions/node/v18.17.0/bin/solcjs -o "/Users/nileshgupta/Desktop/Algorand/gearbot/contracts/.certora_internal/23_11_19_00_21_08_568/.certora_config/GearSparkbot.sol_0/" --overwrite --allow-paths "/Users/nileshgupta/Desktop/Algorand/gearbot/contracts","lib/1inch","lib/aave-v3-core","lib/forge-std/lib/ds-test/src","lib/forge-std/src","lib/gearbox-protocol","lib/openzeppelin-contracts","lib/spark",. --standard-json
stdout, stderr = /Users/nileshgupta/Desktop/Algorand/gearbot/contracts/.certora_internal/23_11_19_00_21_08_568/.certora_config/GearSparkbot.sol_0.standard.json.stdout, /Users/nileshgupta/Desktop/Algorand/gearbot/contracts/.certora_internal/23_11_19_00_21_08_568/.certora_config/GearSparkbot.sol_0.standard.json.stderr
build failed
Failure traceback: 
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/certora_cli/certoraRun.py", line 107, in run_certora
    build(context, ignore_spec_syntax_check=is_library)
  File "/opt/homebrew/lib/python3.11/site-packages/certora_cli/EVMVerifier/certoraBuild.py", line 3551, in build
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/certora_cli/EVMVerifier/certoraBuild.py", line 3524, in build
    certora_build_generator.build()
  File "/opt/homebrew/lib/python3.11/site-packages/certora_cli/EVMVerifier/certoraBuild.py", line 2503, in build
    sdc_pre_finders = self.collect_for_file(build_arg_contract_file, i, compiler_lang, Path(os.getcwd()))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/certora_cli/EVMVerifier/certoraBuild.py", line 1810, in collect_for_file
    Util.run_compiler_cmd(collect_cmd, f"{sdc_name}.standard.json", self.config_path, wd=compile_wd,
  File "/opt/homebrew/lib/python3.11/site-packages/certora_cli/Shared/certoraUtils.py", line 1057, in run_compiler_cmd
    raise Exception(msg)
Exception: Failed to run /Users/nileshgupta/.nvm/versions/node/v18.17.0/bin/solcjs -o "/Users/nileshgupta/Desktop/Algorand/gearbot/contracts/.certora_internal/23_11_19_00_21_08_568/.certora_config/GearSparkbot.sol_0/" --overwrite --allow-paths "/Users/nileshgupta/Desktop/Algorand/gearbot/contracts","lib/1inch","lib/aave-v3-core","lib/forge-std/lib/ds-test/src","lib/forge-std/src","lib/gearbox-protocol","lib/openzeppelin-contracts","lib/spark",. --standard-json, exit code 1
Encountered an error running Certora Prover, please contact Certora
